services:
  - type: web
    name: meu-contador
    runtime: node
    rootDir: backend
    buildCommand: npm install --ignore-scripts && cd backend && npm install && npx prisma generate && npm run build
    startCommand: cd backend && node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: PLUGGY_CLIENT_ID
        sync: false
      - key: PLUGGY_CLIENT_SECRET
        sync: false
      - key: PUBLIC_VAPID_KEY
        sync: false
      - key: PRIVATE_VAPID_KEY
        sync: false
      - key: BRAPI_TOKEN
        sync: false
