import type {
  OnboardingBudget,
  OnboardingGoal,
  OnboardingReminder,
} from "./index";

// ============= Preset Templates =============
export const financialGoalTemplates = {
  save: {
    name: "Economizar",
    icon: "💰",
    description: "Construir reserva e economizar dinheiro",
  },
  invest: {
    name: "Investir",
    icon: "📈",
    description: "Fazer seu dinheiro trabalhar para você",
  },
  "debt-free": {
    name: "Quitar Dívidas",
    icon: "🎯",
    description: "Eliminar dívidas e ficar no positivo",
  },
  emergency: {
    name: "Reserva de Emergência",
    icon: "🛡️",
    description: "6 meses de despesas guardados",
  },
  travel: {
    name: "Viajar",
    icon: "✈️",
    description: "Realizar a viagem dos sonhos",
  },
  house: {
    name: "Casa Própria",
    icon: "🏠",
    description: "Entrada ou compra de imóvel",
  },
  retire: {
    name: "Aposentadoria",
    icon: "🏖️",
    description: "Independência financeira",
  },
};

export const budgetTemplates: Record<string, OnboardingBudget[]> = {
  conservative: [
    {
      category: "Moradia",
      percentage: 30,
      amount: 0,
      priority: "essential",
      enabled: true,
    },
    {
      category: "Alimentação",
      percentage: 15,
      amount: 0,
      priority: "essential",
      enabled: true,
    },
    {
      category: "Transporte",
      percentage: 10,
      amount: 0,
      priority: "essential",
      enabled: true,
    },
    {
      category: "Saúde",
      percentage: 5,
      amount: 0,
      priority: "essential",
      enabled: true,
    },
    {
      category: "Contas",
      percentage: 10,
      amount: 0,
      priority: "essential",
      enabled: true,
    },
    {
      category: "Lazer",
      percentage: 5,
      amount: 0,
      priority: "optional",
      enabled: true,
    },
    {
      category: "Educação",
      percentage: 5,
      amount: 0,
      priority: "important",
      enabled: true,
    },
    {
      category: "Reserva/Investimento",
      percentage: 20,
      amount: 0,
      priority: "essential",
      enabled: true,
    },
  ],
  moderate: [
    {
      category: "Moradia",
      percentage: 28,
      amount: 0,
      priority: "essential",
      enabled: true,
    },
    {
      category: "Alimentação",
      percentage: 12,
      amount: 0,
      priority: "essential",
      enabled: true,
    },
    {
      category: "Transporte",
      percentage: 10,
      amount: 0,
      priority: "essential",
      enabled: true,
    },
    {
      category: "Saúde",
      percentage: 5,
      amount: 0,
      priority: "essential",
      enabled: true,
    },
    {
      category: "Contas",
      percentage: 8,
      amount: 0,
      priority: "essential",
      enabled: true,
    },
    {
      category: "Lazer",
      percentage: 10,
      amount: 0,
      priority: "important",
      enabled: true,
    },
    {
      category: "Educação",
      percentage: 7,
      amount: 0,
      priority: "important",
      enabled: true,
    },
    {
      category: "Reserva/Investimento",
      percentage: 20,
      amount: 0,
      priority: "essential",
      enabled: true,
    },
  ],
  aggressive: [
    {
      category: "Moradia",
      percentage: 25,
      amount: 0,
      priority: "essential",
      enabled: true,
    },
    {
      category: "Alimentação",
      percentage: 10,
      amount: 0,
      priority: "essential",
      enabled: true,
    },
    {
      category: "Transporte",
      percentage: 8,
      amount: 0,
      priority: "essential",
      enabled: true,
    },
    {
      category: "Saúde",
      percentage: 5,
      amount: 0,
      priority: "essential",
      enabled: true,
    },
    {
      category: "Contas",
      percentage: 7,
      amount: 0,
      priority: "essential",
      enabled: true,
    },
    {
      category: "Lazer",
      percentage: 5,
      amount: 0,
      priority: "optional",
      enabled: true,
    },
    {
      category: "Educação",
      percentage: 5,
      amount: 0,
      priority: "important",
      enabled: true,
    },
    {
      category: "Reserva/Investimento",
      percentage: 35,
      amount: 0,
      priority: "essential",
      enabled: true,
    },
  ],
};

export const commonBillReminders: OnboardingReminder[] = [
  {
    name: "Aluguel/Financiamento",
    amount: 0,
    dueDay: 5,
    category: "Moradia",
    enabled: false,
  },
  {
    name: "Condomínio",
    amount: 0,
    dueDay: 10,
    category: "Moradia",
    enabled: false,
  },
  {
    name: "Energia Elétrica",
    amount: 0,
    dueDay: 15,
    category: "Contas",
    enabled: false,
  },
  { name: "Água", amount: 0, dueDay: 20, category: "Contas", enabled: false },
  {
    name: "Internet",
    amount: 0,
    dueDay: 10,
    category: "Contas",
    enabled: false,
  },
  {
    name: "Celular",
    amount: 0,
    dueDay: 15,
    category: "Contas",
    enabled: false,
  },
  {
    name: "Streaming (Netflix, etc)",
    amount: 0,
    dueDay: 1,
    category: "Lazer",
    enabled: false,
  },
  { name: "Academia", amount: 0, dueDay: 5, category: "Saúde", enabled: false },
  {
    name: "Plano de Saúde",
    amount: 0,
    dueDay: 10,
    category: "Saúde",
    enabled: false,
  },
  {
    name: "Cartão de Crédito",
    amount: 0,
    dueDay: 25,
    category: "Outros",
    enabled: false,
  },
  {
    name: "Seguro do Carro",
    amount: 0,
    dueDay: 15,
    category: "Transporte",
    enabled: false,
  },
  {
    name: "Parcela do Carro",
    amount: 0,
    dueDay: 10,
    category: "Transporte",
    enabled: false,
  },
];

export const goalPresets: OnboardingGoal[] = [
  {
    name: "Reserva de Emergência",
    icon: "🛡️",
    targetAmount: 10000,
    deadline: "",
    priority: 1,
    enabled: false,
  },
  {
    name: "Viagem dos Sonhos",
    icon: "✈️",
    targetAmount: 5000,
    deadline: "",
    priority: 2,
    enabled: false,
  },
  {
    name: "Carro Novo",
    icon: "🚗",
    targetAmount: 50000,
    deadline: "",
    priority: 3,
    enabled: false,
  },
  {
    name: "Entrada Casa",
    icon: "🏠",
    targetAmount: 100000,
    deadline: "",
    priority: 4,
    enabled: false,
  },
  {
    name: "Estudos/Cursos",
    icon: "🎓",
    targetAmount: 3000,
    deadline: "",
    priority: 5,
    enabled: false,
  },
  {
    name: "Celular/Eletrônicos",
    icon: "📱",
    targetAmount: 3000,
    deadline: "",
    priority: 6,
    enabled: false,
  },
  {
    name: "Casamento",
    icon: "💍",
    targetAmount: 30000,
    deadline: "",
    priority: 7,
    enabled: false,
  },
  {
    name: "Aposentadoria",
    icon: "🏖️",
    targetAmount: 500000,
    deadline: "",
    priority: 8,
    enabled: false,
  },
];
